AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'Rakefile'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/rails_helper.rb'
    - 'Gemfile'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 125

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ArgumentsForwarding:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/FirstArgumentIndentation:
  Exclude:
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'

Lint/AmbiguousRange:
  Exclude:
    - 'app/models/validators/time_slot_overlap_validator.rb'

Lint/RequireRangeParentheses:
  Exclude:
    - 'app/models/validators/time_slot_overlap_validator.rb'

Lint/EmptyWhen:
  Exclude:
    - 'app/models/validators/time_slot_overlap_validator.rb'
